# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'gui.ui'
##
## Created by: Qt User Interface Compiler version 6.2.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCharts import QChartView
from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractScrollArea, QAbstractSpinBox, QApplication, QComboBox,
    QFrame, QHBoxLayout, QLabel, QMainWindow,
    QPushButton, QSizePolicy, QSpinBox, QVBoxLayout,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setWindowModality(Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(1158, 716)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet(u"background-color: rgb(43, 43, 43);")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.horizontalLayout = QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.user_fr = QFrame(self.centralwidget)
        self.user_fr.setObjectName(u"user_fr")
        sizePolicy1 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.user_fr.sizePolicy().hasHeightForWidth())
        self.user_fr.setSizePolicy(sizePolicy1)
        self.user_fr.setMinimumSize(QSize(0, 60))
        self.user_fr.setMaximumSize(QSize(300, 16777215))
        self.user_fr.setStyleSheet(u"background-color: rgb(56, 56, 56);")
        self.user_fr.setFrameShape(QFrame.Box)
        self.user_fr.setFrameShadow(QFrame.Plain)
        self.verticalLayout = QVBoxLayout(self.user_fr)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(7, 7, 7, -1)
        self.title_fr = QFrame(self.user_fr)
        self.title_fr.setObjectName(u"title_fr")
        self.title_fr.setMinimumSize(QSize(0, 80))
        self.title_fr.setMaximumSize(QSize(16777215, 80))
        self.title_fr.setStyleSheet(u"background-color: rgb(84, 84, 84);")
        self.title_fr.setFrameShape(QFrame.Box)
        self.title_fr.setFrameShadow(QFrame.Plain)
        self.horizontalLayout_2 = QHBoxLayout(self.title_fr)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(-1, 9, -1, -1)
        self.title_icon = QLabel(self.title_fr)
        self.title_icon.setObjectName(u"title_icon")
        self.title_icon.setEnabled(True)
        self.title_icon.setMinimumSize(QSize(50, 60))
        self.title_icon.setMaximumSize(QSize(50, 60))
        self.title_icon.setPixmap(QPixmap(u":/icons/waschmaschine.png"))
        self.title_icon.setScaledContents(True)

        self.horizontalLayout_2.addWidget(self.title_icon)

        self.title_lbl = QLabel(self.title_fr)
        self.title_lbl.setObjectName(u"title_lbl")
        self.title_lbl.setMinimumSize(QSize(0, 0))
        self.title_lbl.setMaximumSize(QSize(90, 16777215))
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setStyleStrategy(QFont.PreferAntialias)
        self.title_lbl.setFont(font)
        self.title_lbl.setStyleSheet(u"color: rgb(248, 248, 248);")
        self.title_lbl.setScaledContents(False)
        self.title_lbl.setAlignment(Qt.AlignCenter)
        self.title_lbl.setWordWrap(True)

        self.horizontalLayout_2.addWidget(self.title_lbl)


        self.verticalLayout.addWidget(self.title_fr)

        self.states_fitting_fr = QFrame(self.user_fr)
        self.states_fitting_fr.setObjectName(u"states_fitting_fr")
        self.states_fitting_fr.setFrameShape(QFrame.NoFrame)
        self.states_fitting_fr.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_15 = QHBoxLayout(self.states_fitting_fr)
        self.horizontalLayout_15.setObjectName(u"horizontalLayout_15")
        self.horizontalLayout_15.setContentsMargins(0, 20, 0, 0)
        self.states_fr = QFrame(self.states_fitting_fr)
        self.states_fr.setObjectName(u"states_fr")
        sizePolicy2 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Maximum)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.states_fr.sizePolicy().hasHeightForWidth())
        self.states_fr.setSizePolicy(sizePolicy2)
        self.states_fr.setMaximumSize(QSize(220, 250))
        self.states_fr.setStyleSheet(u"background-color: rgb(32, 31, 33);")
        self.states_fr.setFrameShape(QFrame.Box)
        self.states_fr.setFrameShadow(QFrame.Raised)
        self.verticalLayout_5 = QVBoxLayout(self.states_fr)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.verticalLayout_5.setContentsMargins(0, 2, 0, 0)
        self.standstill_fr = QFrame(self.states_fr)
        self.standstill_fr.setObjectName(u"standstill_fr")
        sizePolicy3 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.standstill_fr.sizePolicy().hasHeightForWidth())
        self.standstill_fr.setSizePolicy(sizePolicy3)
        self.standstill_fr.setMinimumSize(QSize(0, 0))
        self.standstill_fr.setFrameShape(QFrame.NoFrame)
        self.standstill_fr.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_5 = QHBoxLayout(self.standstill_fr)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(15, 5, 9, 0)
        self.standstill_light = QLabel(self.standstill_fr)
        self.standstill_light.setObjectName(u"standstill_light")
        self.standstill_light.setEnabled(False)
        self.standstill_light.setMinimumSize(QSize(30, 30))
        self.standstill_light.setMaximumSize(QSize(30, 30))
        self.standstill_light.setPixmap(QPixmap(u":/icons/lampe_1.png"))
        self.standstill_light.setScaledContents(True)

        self.horizontalLayout_5.addWidget(self.standstill_light)

        self.standstill_lbl = QLabel(self.standstill_fr)
        self.standstill_lbl.setObjectName(u"standstill_lbl")
        font1 = QFont()
        font1.setPointSize(12)
        font1.setBold(True)
        self.standstill_lbl.setFont(font1)
        self.standstill_lbl.setStyleSheet(u"color: rgb(136, 136, 136);")
        self.standstill_lbl.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.standstill_lbl.setWordWrap(False)

        self.horizontalLayout_5.addWidget(self.standstill_lbl, 0, Qt.AlignVCenter)


        self.verticalLayout_5.addWidget(self.standstill_fr, 0, Qt.AlignVCenter)

        self.pump_in_fr = QFrame(self.states_fr)
        self.pump_in_fr.setObjectName(u"pump_in_fr")
        sizePolicy3.setHeightForWidth(self.pump_in_fr.sizePolicy().hasHeightForWidth())
        self.pump_in_fr.setSizePolicy(sizePolicy3)
        self.pump_in_fr.setMinimumSize(QSize(0, 0))
        self.pump_in_fr.setFrameShape(QFrame.NoFrame)
        self.pump_in_fr.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_17 = QHBoxLayout(self.pump_in_fr)
        self.horizontalLayout_17.setObjectName(u"horizontalLayout_17")
        self.horizontalLayout_17.setContentsMargins(15, 0, 9, 0)
        self.pump_in_light = QLabel(self.pump_in_fr)
        self.pump_in_light.setObjectName(u"pump_in_light")
        self.pump_in_light.setEnabled(False)
        self.pump_in_light.setMinimumSize(QSize(30, 30))
        self.pump_in_light.setMaximumSize(QSize(30, 30))
        self.pump_in_light.setPixmap(QPixmap(u":/icons/lampe_1.png"))
        self.pump_in_light.setScaledContents(True)

        self.horizontalLayout_17.addWidget(self.pump_in_light)

        self.pump_in_lbl = QLabel(self.pump_in_fr)
        self.pump_in_lbl.setObjectName(u"pump_in_lbl")
        self.pump_in_lbl.setFont(font1)
        self.pump_in_lbl.setStyleSheet(u"color: rgb(136, 136, 136);")
        self.pump_in_lbl.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.pump_in_lbl.setWordWrap(False)

        self.horizontalLayout_17.addWidget(self.pump_in_lbl, 0, Qt.AlignVCenter)


        self.verticalLayout_5.addWidget(self.pump_in_fr)

        self.washing_fr = QFrame(self.states_fr)
        self.washing_fr.setObjectName(u"washing_fr")
        self.washing_fr.setFrameShape(QFrame.NoFrame)
        self.washing_fr.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_10 = QHBoxLayout(self.washing_fr)
        self.horizontalLayout_10.setObjectName(u"horizontalLayout_10")
        self.horizontalLayout_10.setContentsMargins(15, 0, -1, 0)
        self.washing_light = QLabel(self.washing_fr)
        self.washing_light.setObjectName(u"washing_light")
        self.washing_light.setEnabled(False)
        self.washing_light.setMinimumSize(QSize(30, 30))
        self.washing_light.setMaximumSize(QSize(30, 30))
        self.washing_light.setPixmap(QPixmap(u":/icons/lampe_1.png"))
        self.washing_light.setScaledContents(True)

        self.horizontalLayout_10.addWidget(self.washing_light)

        self.washing_lbl = QLabel(self.washing_fr)
        self.washing_lbl.setObjectName(u"washing_lbl")
        self.washing_lbl.setFont(font1)
        self.washing_lbl.setStyleSheet(u"color: rgb(136, 136, 136);")

        self.horizontalLayout_10.addWidget(self.washing_lbl, 0, Qt.AlignVCenter)


        self.verticalLayout_5.addWidget(self.washing_fr, 0, Qt.AlignVCenter)

        self.pump_out_fr = QFrame(self.states_fr)
        self.pump_out_fr.setObjectName(u"pump_out_fr")
        self.pump_out_fr.setFrameShape(QFrame.NoFrame)
        self.pump_out_fr.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_9 = QHBoxLayout(self.pump_out_fr)
        self.horizontalLayout_9.setObjectName(u"horizontalLayout_9")
        self.horizontalLayout_9.setContentsMargins(15, 0, -1, 0)
        self.pump_out_light = QLabel(self.pump_out_fr)
        self.pump_out_light.setObjectName(u"pump_out_light")
        self.pump_out_light.setEnabled(False)
        self.pump_out_light.setMinimumSize(QSize(30, 30))
        self.pump_out_light.setMaximumSize(QSize(30, 30))
        self.pump_out_light.setPixmap(QPixmap(u":/icons/lampe_1.png"))
        self.pump_out_light.setScaledContents(True)

        self.horizontalLayout_9.addWidget(self.pump_out_light)

        self.pump_out_lbl = QLabel(self.pump_out_fr)
        self.pump_out_lbl.setObjectName(u"pump_out_lbl")
        self.pump_out_lbl.setFont(font1)
        self.pump_out_lbl.setStyleSheet(u"color: rgb(136, 136, 136);")

        self.horizontalLayout_9.addWidget(self.pump_out_lbl, 0, Qt.AlignVCenter)


        self.verticalLayout_5.addWidget(self.pump_out_fr)

        self.spinning_fr = QFrame(self.states_fr)
        self.spinning_fr.setObjectName(u"spinning_fr")
        self.spinning_fr.setFrameShape(QFrame.NoFrame)
        self.spinning_fr.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_8 = QHBoxLayout(self.spinning_fr)
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.horizontalLayout_8.setContentsMargins(15, 0, -1, 5)
        self.spinning_light = QLabel(self.spinning_fr)
        self.spinning_light.setObjectName(u"spinning_light")
        self.spinning_light.setEnabled(False)
        self.spinning_light.setMinimumSize(QSize(30, 30))
        self.spinning_light.setMaximumSize(QSize(30, 30))
        self.spinning_light.setPixmap(QPixmap(u":/icons/lampe_1.png"))
        self.spinning_light.setScaledContents(True)

        self.horizontalLayout_8.addWidget(self.spinning_light)

        self.spinning_lbl = QLabel(self.spinning_fr)
        self.spinning_lbl.setObjectName(u"spinning_lbl")
        self.spinning_lbl.setFont(font1)
        self.spinning_lbl.setStyleSheet(u"color: rgb(136, 136, 136);")

        self.horizontalLayout_8.addWidget(self.spinning_lbl, 0, Qt.AlignVCenter)


        self.verticalLayout_5.addWidget(self.spinning_fr)


        self.horizontalLayout_15.addWidget(self.states_fr)


        self.verticalLayout.addWidget(self.states_fitting_fr, 0, Qt.AlignTop)

        self.menue_fr = QFrame(self.user_fr)
        self.menue_fr.setObjectName(u"menue_fr")
        self.menue_fr.setEnabled(True)
        sizePolicy4 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.menue_fr.sizePolicy().hasHeightForWidth())
        self.menue_fr.setSizePolicy(sizePolicy4)
        self.menue_fr.setMinimumSize(QSize(0, 0))
        self.menue_fr.setFrameShape(QFrame.NoFrame)
        self.menue_fr.setFrameShadow(QFrame.Raised)
        self.verticalLayout_3 = QVBoxLayout(self.menue_fr)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.info_fr = QFrame(self.menue_fr)
        self.info_fr.setObjectName(u"info_fr")
        sizePolicy2.setHeightForWidth(self.info_fr.sizePolicy().hasHeightForWidth())
        self.info_fr.setSizePolicy(sizePolicy2)
        self.info_fr.setMinimumSize(QSize(0, 0))
        self.info_fr.setMaximumSize(QSize(235, 50))
        self.info_fr.setStyleSheet(u"background-color: rgb(243, 243, 243);")
        self.info_fr.setFrameShape(QFrame.Panel)
        self.info_fr.setFrameShadow(QFrame.Plain)
        self.verticalLayout_10 = QVBoxLayout(self.info_fr)
        self.verticalLayout_10.setObjectName(u"verticalLayout_10")
        self.verticalLayout_10.setContentsMargins(2, 2, 2, 2)
        self.first_info_lbl = QLabel(self.info_fr)
        self.first_info_lbl.setObjectName(u"first_info_lbl")
        font2 = QFont()
        font2.setPointSize(8)
        self.first_info_lbl.setFont(font2)
        self.first_info_lbl.setStyleSheet(u"")
        self.first_info_lbl.setLineWidth(0)

        self.verticalLayout_10.addWidget(self.first_info_lbl)

        self.second_info_lbl = QLabel(self.info_fr)
        self.second_info_lbl.setObjectName(u"second_info_lbl")
        self.second_info_lbl.setFont(font2)
        self.second_info_lbl.setStyleSheet(u"")
        self.second_info_lbl.setLineWidth(0)

        self.verticalLayout_10.addWidget(self.second_info_lbl)


        self.verticalLayout_3.addWidget(self.info_fr)

        self.connection_fr = QFrame(self.menue_fr)
        self.connection_fr.setObjectName(u"connection_fr")
        self.connection_fr.setEnabled(True)
        sizePolicy5 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Minimum)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.connection_fr.sizePolicy().hasHeightForWidth())
        self.connection_fr.setSizePolicy(sizePolicy5)
        self.connection_fr.setMinimumSize(QSize(220, 0))
        self.connection_fr.setStyleSheet(u"background-color: rgb(98, 98, 98);")
        self.connection_fr.setFrameShape(QFrame.Box)
        self.connection_fr.setFrameShadow(QFrame.Plain)
        self.connection_fr.setLineWidth(1)
        self.connection_fr.setMidLineWidth(0)
        self.horizontalLayout_7 = QHBoxLayout(self.connection_fr)
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.horizontalLayout_7.setContentsMargins(8, 9, 8, 8)
        self.frequency_label = QLabel(self.connection_fr)
        self.frequency_label.setObjectName(u"frequency_label")
        self.frequency_label.setMaximumSize(QSize(100, 16777215))
        font3 = QFont()
        font3.setPointSize(8)
        font3.setBold(True)
        self.frequency_label.setFont(font3)
        self.frequency_label.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.frequency_label.setWordWrap(True)

        self.horizontalLayout_7.addWidget(self.frequency_label, 0, Qt.AlignLeft)

        self.frequency_spinButton = QSpinBox(self.connection_fr)
        self.frequency_spinButton.setObjectName(u"frequency_spinButton")
        self.frequency_spinButton.setEnabled(False)
        self.frequency_spinButton.setMinimumSize(QSize(45, 0))
        self.frequency_spinButton.setMaximumSize(QSize(50, 16777215))
        self.frequency_spinButton.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.frequency_spinButton.setFrame(False)
        self.frequency_spinButton.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.frequency_spinButton.setButtonSymbols(QAbstractSpinBox.UpDownArrows)
        self.frequency_spinButton.setMinimum(5)
        self.frequency_spinButton.setMaximum(200)
        self.frequency_spinButton.setSingleStep(5)
        self.frequency_spinButton.setValue(100)

        self.horizontalLayout_7.addWidget(self.frequency_spinButton)

        self.connect_to_esp_cmd = QPushButton(self.connection_fr)
        self.connect_to_esp_cmd.setObjectName(u"connect_to_esp_cmd")
        self.connect_to_esp_cmd.setEnabled(False)
        sizePolicy6 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy6.setHorizontalStretch(0)
        sizePolicy6.setVerticalStretch(0)
        sizePolicy6.setHeightForWidth(self.connect_to_esp_cmd.sizePolicy().hasHeightForWidth())
        self.connect_to_esp_cmd.setSizePolicy(sizePolicy6)
        self.connect_to_esp_cmd.setMinimumSize(QSize(0, 0))
        self.connect_to_esp_cmd.setAutoFillBackground(False)
        self.connect_to_esp_cmd.setStyleSheet(u"background-color: rgb(98, 98, 98);\n"
"color: rgb(255, 255, 255);")
        self.connect_to_esp_cmd.setInputMethodHints(Qt.ImhMultiLine)
        self.connect_to_esp_cmd.setAutoExclusive(False)
        self.connect_to_esp_cmd.setFlat(False)

        self.horizontalLayout_7.addWidget(self.connect_to_esp_cmd, 0, Qt.AlignBottom)


        self.verticalLayout_3.addWidget(self.connection_fr, 0, Qt.AlignLeft|Qt.AlignTop)

        self.history_fr = QFrame(self.menue_fr)
        self.history_fr.setObjectName(u"history_fr")
        self.history_fr.setEnabled(True)
        sizePolicy5.setHeightForWidth(self.history_fr.sizePolicy().hasHeightForWidth())
        self.history_fr.setSizePolicy(sizePolicy5)
        self.history_fr.setMinimumSize(QSize(0, 80))
        self.history_fr.setStyleSheet(u"background-color: rgb(46, 46, 68);")
        self.history_fr.setFrameShape(QFrame.Box)
        self.history_fr.setFrameShadow(QFrame.Plain)
        self.verticalLayout_11 = QVBoxLayout(self.history_fr)
        self.verticalLayout_11.setObjectName(u"verticalLayout_11")
        self.verticalLayout_11.setContentsMargins(8, 8, 8, 8)
        self.saved_data_fr = QFrame(self.history_fr)
        self.saved_data_fr.setObjectName(u"saved_data_fr")
        self.saved_data_fr.setFrameShape(QFrame.NoFrame)
        self.saved_data_fr.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_14 = QHBoxLayout(self.saved_data_fr)
        self.horizontalLayout_14.setObjectName(u"horizontalLayout_14")
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.saved_data_lbl = QLabel(self.saved_data_fr)
        self.saved_data_lbl.setObjectName(u"saved_data_lbl")
        self.saved_data_lbl.setMaximumSize(QSize(100, 16777215))
        self.saved_data_lbl.setFont(font3)
        self.saved_data_lbl.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.saved_data_lbl.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.horizontalLayout_14.addWidget(self.saved_data_lbl, 0, Qt.AlignLeft)

        self.saved_data_cb = QComboBox(self.saved_data_fr)
        self.saved_data_cb.setObjectName(u"saved_data_cb")
        self.saved_data_cb.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.saved_data_cb.sizePolicy().hasHeightForWidth())
        self.saved_data_cb.setSizePolicy(sizePolicy1)
        self.saved_data_cb.setMinimumSize(QSize(200, 0))
        font4 = QFont()
        font4.setPointSize(10)
        font4.setKerning(False)
        self.saved_data_cb.setFont(font4)
        self.saved_data_cb.setAutoFillBackground(False)
        self.saved_data_cb.setStyleSheet(u"background-color: rgb(100, 104, 126);\n"
"color: rgb(255, 255, 255);")
        self.saved_data_cb.setMaxVisibleItems(5)
        self.saved_data_cb.setSizeAdjustPolicy(QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.saved_data_cb.setIconSize(QSize(10, 10))

        self.horizontalLayout_14.addWidget(self.saved_data_cb, 0, Qt.AlignBottom)


        self.verticalLayout_11.addWidget(self.saved_data_fr)

        self.axis_to_plot_fr = QFrame(self.history_fr)
        self.axis_to_plot_fr.setObjectName(u"axis_to_plot_fr")
        self.axis_to_plot_fr.setFrameShape(QFrame.NoFrame)
        self.axis_to_plot_fr.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_6 = QHBoxLayout(self.axis_to_plot_fr)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.axis_to_plot_lbl = QLabel(self.axis_to_plot_fr)
        self.axis_to_plot_lbl.setObjectName(u"axis_to_plot_lbl")
        self.axis_to_plot_lbl.setMaximumSize(QSize(170, 16777215))
        self.axis_to_plot_lbl.setFont(font3)
        self.axis_to_plot_lbl.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.axis_to_plot_lbl.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.horizontalLayout_6.addWidget(self.axis_to_plot_lbl, 0, Qt.AlignLeft|Qt.AlignBottom)

        self.axis_to_plot_cb = QComboBox(self.axis_to_plot_fr)
        self.axis_to_plot_cb.setObjectName(u"axis_to_plot_cb")
        self.axis_to_plot_cb.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.axis_to_plot_cb.sizePolicy().hasHeightForWidth())
        self.axis_to_plot_cb.setSizePolicy(sizePolicy1)
        self.axis_to_plot_cb.setMinimumSize(QSize(70, 0))
        self.axis_to_plot_cb.setFont(font4)
        self.axis_to_plot_cb.setAutoFillBackground(False)
        self.axis_to_plot_cb.setStyleSheet(u"background-color: rgb(100, 104, 126);\n"
"color: rgb(255, 255, 255);")
        self.axis_to_plot_cb.setSizeAdjustPolicy(QComboBox.AdjustToMinimumContentsLengthWithIcon)
        self.axis_to_plot_cb.setIconSize(QSize(10, 10))
        self.axis_to_plot_cb.setFrame(True)

        self.horizontalLayout_6.addWidget(self.axis_to_plot_cb, 0, Qt.AlignBottom)


        self.verticalLayout_11.addWidget(self.axis_to_plot_fr)

        self.history_button_fr = QFrame(self.history_fr)
        self.history_button_fr.setObjectName(u"history_button_fr")
        self.history_button_fr.setFrameShape(QFrame.NoFrame)
        self.history_button_fr.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_11 = QHBoxLayout(self.history_button_fr)
        self.horizontalLayout_11.setObjectName(u"horizontalLayout_11")
        self.horizontalLayout_11.setContentsMargins(0, 5, 0, 0)
        self.start_simulation_cmd = QPushButton(self.history_button_fr)
        self.start_simulation_cmd.setObjectName(u"start_simulation_cmd")
        self.start_simulation_cmd.setEnabled(False)
        self.start_simulation_cmd.setMinimumSize(QSize(0, 0))
        self.start_simulation_cmd.setStyleSheet(u"background-color: rgb(98, 98, 98);\n"
"color: rgb(255, 255, 255);")

        self.horizontalLayout_11.addWidget(self.start_simulation_cmd)

        self.show_history_cmd = QPushButton(self.history_button_fr)
        self.show_history_cmd.setObjectName(u"show_history_cmd")
        self.show_history_cmd.setEnabled(True)
        self.show_history_cmd.setMinimumSize(QSize(0, 0))
        self.show_history_cmd.setStyleSheet(u"background-color: rgb(100, 104, 126);\n"
"color: rgb(255, 255, 255);")

        self.horizontalLayout_11.addWidget(self.show_history_cmd)


        self.verticalLayout_11.addWidget(self.history_button_fr)


        self.verticalLayout_3.addWidget(self.history_fr, 0, Qt.AlignBottom)

        self.creator_fr = QFrame(self.menue_fr)
        self.creator_fr.setObjectName(u"creator_fr")
        self.creator_fr.setMinimumSize(QSize(0, 0))
        self.creator_fr.setMaximumSize(QSize(16777215, 80))
        self.creator_fr.setFrameShape(QFrame.NoFrame)
        self.creator_fr.setFrameShadow(QFrame.Raised)
        self.verticalLayout_22 = QVBoxLayout(self.creator_fr)
        self.verticalLayout_22.setObjectName(u"verticalLayout_22")
        self.verticalLayout_22.setContentsMargins(0, 9, -1, 0)
        self.creator_lbl = QLabel(self.creator_fr)
        self.creator_lbl.setObjectName(u"creator_lbl")
        font5 = QFont()
        font5.setPointSize(7)
        font5.setBold(True)
        font5.setStyleStrategy(QFont.PreferAntialias)
        self.creator_lbl.setFont(font5)
        self.creator_lbl.setStyleSheet(u"color: rgb(248, 248, 248);")

        self.verticalLayout_22.addWidget(self.creator_lbl, 0, Qt.AlignBottom)


        self.verticalLayout_3.addWidget(self.creator_fr)


        self.verticalLayout.addWidget(self.menue_fr, 0, Qt.AlignBottom)


        self.horizontalLayout.addWidget(self.user_fr)

        self.data_fr = QFrame(self.centralwidget)
        self.data_fr.setObjectName(u"data_fr")
        sizePolicy3.setHeightForWidth(self.data_fr.sizePolicy().hasHeightForWidth())
        self.data_fr.setSizePolicy(sizePolicy3)
        self.data_fr.setFrameShape(QFrame.NoFrame)
        self.data_fr.setFrameShadow(QFrame.Raised)
        self.verticalLayout_2 = QVBoxLayout(self.data_fr)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(3, 0, 0, 0)
        self.process_fr = QFrame(self.data_fr)
        self.process_fr.setObjectName(u"process_fr")
        self.process_fr.setMaximumSize(QSize(16777215, 99))
        self.process_fr.setFrameShape(QFrame.Box)
        self.process_fr.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_4 = QHBoxLayout(self.process_fr)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(-1, 8, -1, 9)
        self.freq_send_ico = QLabel(self.process_fr)
        self.freq_send_ico.setObjectName(u"freq_send_ico")
        self.freq_send_ico.setEnabled(False)
        self.freq_send_ico.setMaximumSize(QSize(70, 60))
        self.freq_send_ico.setStyleSheet(u"")
        self.freq_send_ico.setPixmap(QPixmap(u":/icons/freq_co_ico.png"))
        self.freq_send_ico.setScaledContents(True)

        self.horizontalLayout_4.addWidget(self.freq_send_ico, 0, Qt.AlignHCenter)

        self.machine_fr = QFrame(self.process_fr)
        self.machine_fr.setObjectName(u"machine_fr")
        self.machine_fr.setFrameShape(QFrame.NoFrame)
        self.machine_fr.setFrameShadow(QFrame.Raised)
        self.verticalLayout_12 = QVBoxLayout(self.machine_fr)
        self.verticalLayout_12.setObjectName(u"verticalLayout_12")
        self.verticalLayout_12.setContentsMargins(-1, 0, -1, 0)
        self.machine_ico = QLabel(self.machine_fr)
        self.machine_ico.setObjectName(u"machine_ico")
        self.machine_ico.setEnabled(False)
        self.machine_ico.setMaximumSize(QSize(50, 60))
        self.machine_ico.setInputMethodHints(Qt.ImhNone)
        self.machine_ico.setFrameShape(QFrame.NoFrame)
        self.machine_ico.setFrameShadow(QFrame.Plain)
        self.machine_ico.setMidLineWidth(0)
        self.machine_ico.setTextFormat(Qt.AutoText)
        self.machine_ico.setPixmap(QPixmap(u":/icons/wm_ico.png"))
        self.machine_ico.setScaledContents(True)
        self.machine_ico.setMargin(0)
        self.machine_ico.setIndent(-1)

        self.verticalLayout_12.addWidget(self.machine_ico, 0, Qt.AlignHCenter)

        self.machine_lbl = QLabel(self.machine_fr)
        self.machine_lbl.setObjectName(u"machine_lbl")
        self.machine_lbl.setMinimumSize(QSize(0, 0))
        self.machine_lbl.setMaximumSize(QSize(16777215, 16777215))
        font6 = QFont()
        font6.setBold(True)
        self.machine_lbl.setFont(font6)
        self.machine_lbl.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.machine_lbl.setAlignment(Qt.AlignCenter)

        self.verticalLayout_12.addWidget(self.machine_lbl)


        self.horizontalLayout_4.addWidget(self.machine_fr, 0, Qt.AlignHCenter)

        self.tcp_connection_ico = QLabel(self.process_fr)
        self.tcp_connection_ico.setObjectName(u"tcp_connection_ico")
        self.tcp_connection_ico.setEnabled(False)
        self.tcp_connection_ico.setMinimumSize(QSize(0, 0))
        self.tcp_connection_ico.setMaximumSize(QSize(70, 60))
        self.tcp_connection_ico.setToolTipDuration(-1)
        self.tcp_connection_ico.setAutoFillBackground(False)
        self.tcp_connection_ico.setStyleSheet(u"")
        self.tcp_connection_ico.setInputMethodHints(Qt.ImhNone)
        self.tcp_connection_ico.setTextFormat(Qt.AutoText)
        self.tcp_connection_ico.setPixmap(QPixmap(u":/icons/tcp_co_ico.png"))
        self.tcp_connection_ico.setScaledContents(True)
        self.tcp_connection_ico.setMargin(0)

        self.horizontalLayout_4.addWidget(self.tcp_connection_ico, 0, Qt.AlignHCenter)

        self.gateway_fr = QFrame(self.process_fr)
        self.gateway_fr.setObjectName(u"gateway_fr")
        self.gateway_fr.setFrameShape(QFrame.NoFrame)
        self.gateway_fr.setFrameShadow(QFrame.Raised)
        self.verticalLayout_13 = QVBoxLayout(self.gateway_fr)
        self.verticalLayout_13.setObjectName(u"verticalLayout_13")
        self.verticalLayout_13.setContentsMargins(-1, 0, -1, 0)
        self.gateway_ico = QLabel(self.gateway_fr)
        self.gateway_ico.setObjectName(u"gateway_ico")
        self.gateway_ico.setEnabled(False)
        self.gateway_ico.setMaximumSize(QSize(55, 16777215))
        self.gateway_ico.setPixmap(QPixmap(u":/icons/gateway_ico.png"))
        self.gateway_ico.setScaledContents(True)

        self.verticalLayout_13.addWidget(self.gateway_ico, 0, Qt.AlignHCenter)

        self.gateway_lbl = QLabel(self.gateway_fr)
        self.gateway_lbl.setObjectName(u"gateway_lbl")
        self.gateway_lbl.setMinimumSize(QSize(0, 0))
        self.gateway_lbl.setMaximumSize(QSize(16777215, 16777215))
        self.gateway_lbl.setFont(font6)
        self.gateway_lbl.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.gateway_lbl.setAlignment(Qt.AlignCenter)

        self.verticalLayout_13.addWidget(self.gateway_lbl)


        self.horizontalLayout_4.addWidget(self.gateway_fr, 0, Qt.AlignHCenter)

        self.plus_ico = QLabel(self.process_fr)
        self.plus_ico.setObjectName(u"plus_ico")
        self.plus_ico.setEnabled(False)
        self.plus_ico.setMaximumSize(QSize(70, 60))
        self.plus_ico.setPixmap(QPixmap(u":/icons/gui_co_ico.png"))
        self.plus_ico.setScaledContents(True)

        self.horizontalLayout_4.addWidget(self.plus_ico)

        self.gui_fr = QFrame(self.process_fr)
        self.gui_fr.setObjectName(u"gui_fr")
        self.gui_fr.setFrameShape(QFrame.NoFrame)
        self.gui_fr.setFrameShadow(QFrame.Raised)
        self.verticalLayout_17 = QVBoxLayout(self.gui_fr)
        self.verticalLayout_17.setObjectName(u"verticalLayout_17")
        self.verticalLayout_17.setContentsMargins(-1, 0, -1, 0)
        self.gui_ico = QLabel(self.gui_fr)
        self.gui_ico.setObjectName(u"gui_ico")
        self.gui_ico.setEnabled(False)
        self.gui_ico.setMaximumSize(QSize(55, 16777215))
        self.gui_ico.setPixmap(QPixmap(u":/icons/gui_ico.png"))
        self.gui_ico.setScaledContents(True)

        self.verticalLayout_17.addWidget(self.gui_ico, 0, Qt.AlignHCenter)

        self.gui_lbl = QLabel(self.gui_fr)
        self.gui_lbl.setObjectName(u"gui_lbl")
        self.gui_lbl.setEnabled(True)
        self.gui_lbl.setMaximumSize(QSize(16777215, 16777215))
        self.gui_lbl.setFont(font6)
        self.gui_lbl.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.gui_lbl.setAlignment(Qt.AlignCenter)

        self.verticalLayout_17.addWidget(self.gui_lbl)


        self.horizontalLayout_4.addWidget(self.gui_fr)

        self.data_send_ico = QLabel(self.process_fr)
        self.data_send_ico.setObjectName(u"data_send_ico")
        self.data_send_ico.setEnabled(False)
        self.data_send_ico.setMaximumSize(QSize(70, 30))
        font7 = QFont()
        font7.setKerning(True)
        self.data_send_ico.setFont(font7)
        self.data_send_ico.setAutoFillBackground(False)
        self.data_send_ico.setPixmap(QPixmap(u":/icons/co_ico.png"))
        self.data_send_ico.setScaledContents(True)

        self.horizontalLayout_4.addWidget(self.data_send_ico)

        self.cloud_fr = QFrame(self.process_fr)
        self.cloud_fr.setObjectName(u"cloud_fr")
        self.cloud_fr.setFrameShape(QFrame.NoFrame)
        self.cloud_fr.setFrameShadow(QFrame.Raised)
        self.verticalLayout_14 = QVBoxLayout(self.cloud_fr)
        self.verticalLayout_14.setObjectName(u"verticalLayout_14")
        self.verticalLayout_14.setContentsMargins(-1, 0, -1, 0)
        self.cloud_ico = QLabel(self.cloud_fr)
        self.cloud_ico.setObjectName(u"cloud_ico")
        self.cloud_ico.setEnabled(False)
        self.cloud_ico.setMaximumSize(QSize(80, 16777215))
        self.cloud_ico.setPixmap(QPixmap(u":/icons/database_ico.png"))
        self.cloud_ico.setScaledContents(True)

        self.verticalLayout_14.addWidget(self.cloud_ico, 0, Qt.AlignHCenter)

        self.cloud_lbl = QLabel(self.cloud_fr)
        self.cloud_lbl.setObjectName(u"cloud_lbl")
        self.cloud_lbl.setMinimumSize(QSize(0, 0))
        self.cloud_lbl.setMaximumSize(QSize(16777215, 16777215))
        self.cloud_lbl.setFont(font6)
        self.cloud_lbl.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.cloud_lbl.setAlignment(Qt.AlignCenter)

        self.verticalLayout_14.addWidget(self.cloud_lbl)


        self.horizontalLayout_4.addWidget(self.cloud_fr)


        self.verticalLayout_2.addWidget(self.process_fr)

        self.acce_diagram_fr = QFrame(self.data_fr)
        self.acce_diagram_fr.setObjectName(u"acce_diagram_fr")
        self.acce_diagram_fr.setFrameShape(QFrame.NoFrame)
        self.acce_diagram_fr.setFrameShadow(QFrame.Raised)
        self.verticalLayout_4 = QVBoxLayout(self.acce_diagram_fr)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 10, 0, -1)
        self.acce_chartView = QChartView(self.acce_diagram_fr)
        self.acce_chartView.setObjectName(u"acce_chartView")
        sizePolicy7 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy7.setHorizontalStretch(0)
        sizePolicy7.setVerticalStretch(0)
        sizePolicy7.setHeightForWidth(self.acce_chartView.sizePolicy().hasHeightForWidth())
        self.acce_chartView.setSizePolicy(sizePolicy7)
        font8 = QFont()
        font8.setPointSize(22)
        self.acce_chartView.setFont(font8)
        self.acce_chartView.setFrameShape(QFrame.NoFrame)
        self.acce_chartView.setFrameShadow(QFrame.Plain)
        self.acce_chartView.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.acce_chartView.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.acce_chartView.setSizeAdjustPolicy(QAbstractScrollArea.AdjustIgnored)
        self.acce_chartView.setInteractive(True)

        self.verticalLayout_4.addWidget(self.acce_chartView)


        self.verticalLayout_2.addWidget(self.acce_diagram_fr)


        self.horizontalLayout.addWidget(self.data_fr)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        self.connect_to_esp_cmd.setDefault(False)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Operation condition analysis with MPU6050", None))
        self.title_icon.setText("")
        self.title_lbl.setText(QCoreApplication.translate("MainWindow", u"WASHING MACHINE ANALYSIS", None))
        self.standstill_light.setText("")
        self.standstill_lbl.setText(QCoreApplication.translate("MainWindow", u"Standstill", None))
        self.pump_in_light.setText("")
        self.pump_in_lbl.setText(QCoreApplication.translate("MainWindow", u"Pump in water", None))
        self.washing_light.setText("")
        self.washing_lbl.setText(QCoreApplication.translate("MainWindow", u"Washing | Flushing", None))
        self.pump_out_light.setText("")
        self.pump_out_lbl.setText(QCoreApplication.translate("MainWindow", u"Pump out water", None))
        self.spinning_light.setText("")
        self.spinning_lbl.setText(QCoreApplication.translate("MainWindow", u"Spinning", None))
        self.first_info_lbl.setText("")
        self.second_info_lbl.setText("")
        self.frequency_label.setText(QCoreApplication.translate("MainWindow", u"Frequency:", None))
        self.connect_to_esp_cmd.setText(QCoreApplication.translate("MainWindow", u"Connect to ESP", None))
        self.saved_data_lbl.setText(QCoreApplication.translate("MainWindow", u"Dataset:", None))
        self.saved_data_cb.setCurrentText("")
        self.axis_to_plot_lbl.setText(QCoreApplication.translate("MainWindow", u"Axis to plot:", None))
        self.start_simulation_cmd.setText(QCoreApplication.translate("MainWindow", u"simulate", None))
        self.show_history_cmd.setText(QCoreApplication.translate("MainWindow", u"show", None))
        self.creator_lbl.setText(QCoreApplication.translate("MainWindow", u"Created by David Wergen & Jens Juraschek", None))
        self.freq_send_ico.setText("")
        self.machine_ico.setText("")
        self.machine_lbl.setText(QCoreApplication.translate("MainWindow", u"Prozess", None))
        self.tcp_connection_ico.setText("")
        self.gateway_ico.setText("")
        self.gateway_lbl.setText(QCoreApplication.translate("MainWindow", u"Gateway", None))
        self.plus_ico.setText("")
        self.gui_ico.setText("")
        self.gui_lbl.setText(QCoreApplication.translate("MainWindow", u"GUI", None))
        self.data_send_ico.setText("")
        self.cloud_ico.setText("")
        self.cloud_lbl.setText(QCoreApplication.translate("MainWindow", u"Cloud/Local", None))
    # retranslateUi

